// Default recipe library — sourced from the CaloRhythm app's recipe list.
// This ships as static app data (not a database table) since it's the
// same for every user. "Save a copy for myself" in the UI copies one of
// these into the user's own editable user_recipes.

export const DEFAULT_RECIPE_CATEGORIES = [
  "Keto",
  "Low Carb",
  "Carnivore",
  "Clean Eating",
  "IF Only",
  "Pescatarian",
  "Diabetic-Friendly",
  "Low Sodium",
  "Calorie Deficit",
  "TTC"
]

export const DEFAULT_RECIPES = [
  {
    id: "keto-bacon-egg-cauliflower-skillet",
    category: "Keto",
    title: "Bacon & Egg Cauliflower Skillet",
    yield_text: "1 serving",
    ingredients: "3 strips bacon, chopped\n2 large eggs\n1 cup cauliflower rice\n2 cloves garlic, minced\n1 tbsp butter\nSalt & pepper\nSpring onion",
    procedure: "Cook bacon in pan until crispy. Set aside, keep drippings.\nAdd butter and garlic. Sauté 1 min.\nAdd cauliflower rice. Stir-fry 3–4 min.\nPush to side. Crack eggs in pan, scramble lightly.\nMix everything together. Season well.\nTop with spring onion and bacon. Serve hot.",
    notes: "Per serving: 420 kcal · 4g carbs · 28g protein · 32g fat · 2g sugar · 520mg sodium\nPrep/cook time: 15 min",
  },
  {
    id: "keto-tinola-style-chicken-no-rice",
    category: "Keto",
    title: "Tinola-Style Chicken (No Rice)",
    yield_text: "1 serving",
    ingredients: "200g chicken thighs, bone-in\n½ thumb ginger, sliced\n2 cloves garlic, minced\n½ onion, sliced\n1 cup sayote, cubed\n½ cup malunggay leaves\n1 cup chicken broth\nFish sauce & pepper\n1 tsp oil",
    procedure: "Heat oil. Sauté garlic, onion, ginger until fragrant.\nAdd chicken. Brown on all sides, about 5 min.\nPour in broth. Bring to a boil.\nLower heat. Simmer 15 min until cooked.\nAdd sayote. Cook 5 min until tender.\nAdd malunggay last. Season with fish sauce and pepper.",
    notes: "Per serving: 350 kcal · 6g carbs · 40g protein · 16g fat · 1g sugar · 480mg sodium\nPrep/cook time: 30 min",
  },
  {
    id: "keto-tuna-avocado-keto-bowl",
    category: "Keto",
    title: "Tuna & Avocado Keto Bowl",
    yield_text: "1 serving",
    ingredients: "1 can tuna in water (185g), drained\n½ ripe avocado\n1 tbsp mayonnaise\n1 tbsp calamansi juice\n¼ small red onion, minced\nSalt & pepper\nLettuce leaves",
    procedure: "Drain tuna well. Flake into a bowl.\nMix in mayo, calamansi juice, and red onion.\nSeason with salt and pepper.\nDice avocado and mix into tuna.\nServe on lettuce leaves.\nBest eaten immediately while fresh.",
    notes: "Per serving: 520 kcal · 8g carbs · 38g protein · 36g fat · 1g sugar · 340mg sodium\nPrep/cook time: 10 min",
  },
  {
    id: "keto-pork-belly-lechon-kawali",
    category: "Keto",
    title: "Pork Belly Lechon Kawali",
    yield_text: "1 serving",
    ingredients: "200g pork belly\n½ tsp salt\n½ tsp garlic powder\n¼ tsp black pepper\n1 bay leaf\nWater to boil\nOil for frying",
    procedure: "Boil pork belly with salt, garlic powder, pepper, bay leaf 20 min.\nDrain. Pat very dry with paper towels.\nRest uncovered 10 min to dry skin.\nDeep-fry or air-fry at 200°C for 15–18 min until crispy.\nRest 3 min before cutting.\nServe with vinegar-garlic dipping sauce.",
    notes: "Per serving: 680 kcal · 2g carbs · 32g protein · 60g fat · 0g sugar · 380mg sodium\nPrep/cook time: 45 min",
  },
  {
    id: "keto-giniling-keto-lettuce-wraps",
    category: "Keto",
    title: "Giniling Keto Lettuce Wraps",
    yield_text: "1 serving",
    ingredients: "180g ground pork or beef\n2 cloves garlic, minced\n¼ onion, diced\n1 tbsp soy sauce\n1 tsp oyster sauce\nSalt & pepper\nIceberg lettuce leaves",
    procedure: "Sauté garlic and onion in oil until soft.\nAdd ground meat. Cook until browned.\nSeason with soy sauce, oyster sauce, salt and pepper.\nTaste and adjust seasoning.\nScoop into lettuce cups.\nServe immediately.",
    notes: "Per serving: 380 kcal · 5g carbs · 34g protein · 24g fat · 3g sugar · 560mg sodium\nPrep/cook time: 20 min",
  },
  {
    id: "keto-salmon-with-calamansi-butter",
    category: "Keto",
    title: "Salmon with Calamansi Butter",
    yield_text: "1 serving",
    ingredients: "180g salmon fillet\n2 tbsp butter\n3 calamansi, juiced\n2 cloves garlic, minced\nSalt & pepper\nSpring onion\n1 tbsp oil",
    procedure: "Season salmon with salt and pepper.\nHeat oil in non-stick pan over medium-high heat.\nSear salmon skin-side up 4 min. Flip.\nAdd butter and garlic. Cook 30 sec.\nPour calamansi juice over salmon. Baste 3 min.\nServe with pan sauce and spring onion.",
    notes: "Per serving: 520 kcal · 2g carbs · 42g protein · 38g fat · 0g sugar · 290mg sodium\nPrep/cook time: 20 min",
  },
  {
    id: "low-carb-chicken-arroz-caldo-cauliflower",
    category: "Low Carb",
    title: "Chicken Arroz Caldo (Cauliflower)",
    yield_text: "1 serving",
    ingredients: "150g chicken breast, shredded\n1 cup cauliflower rice\n½ thumb ginger, julienned\n2 cloves garlic, minced\n½ onion, diced\n1.5 cups chicken broth\nFish sauce to taste\n1 tsp oil\n1 boiled egg, spring onion, calamansi to serve",
    procedure: "Sauté garlic, onion, ginger in oil.\nAdd chicken. Stir 2 min.\nPour in broth. Bring to a boil.\nAdd cauliflower rice. Simmer 10 min, stirring.\nSeason with fish sauce.\nTop with boiled egg, spring onion and calamansi.",
    notes: "Per serving: 320 kcal · 10g carbs · 38g protein · 14g fat · 1g sugar · 540mg sodium\nPrep/cook time: 30 min",
  },
  {
    id: "low-carb-grilled-liempo-with-atchara-slaw",
    category: "Low Carb",
    title: "Grilled Liempo with Atchara Slaw",
    yield_text: "1 serving",
    ingredients: "200g pork belly slices\n2 tbsp soy sauce\n1 tbsp calamansi juice\n2 cloves garlic, minced\n½ tsp sugar substitute\n½ cup shredded green papaya\n1 tbsp white vinegar\nSalt & pepper",
    procedure: "Mix soy sauce, calamansi, garlic, sugar sub. Marinate pork 15 min.\nShred papaya. Toss with vinegar and salt. Set aside.\nGrill or pan-fry liempo on high heat 4–5 min per side until charred.\nRest meat 3 min before slicing.\nPlate sliced liempo with papaya slaw.\nServe with extra calamansi.",
    notes: "Per serving: 560 kcal · 6g carbs · 36g protein · 44g fat · 4g sugar · 420mg sodium\nPrep/cook time: 25 min",
  },
  {
    id: "low-carb-bangus-veggie-stir-fry",
    category: "Low Carb",
    title: "Bangus & Veggie Stir-Fry",
    yield_text: "1 serving",
    ingredients: "200g bangus fillet, boneless, cubed\n1 cup mixed vegetables (sitaw, carrots, bell pepper)\n2 cloves garlic\n½ onion, sliced\n1 tbsp soy sauce\n1 tsp oyster sauce\n1 tsp sesame oil\nSalt & pepper\nOil for frying",
    procedure: "Season bangus with salt and pepper. Pan-fry until golden. Set aside.\nIn same pan, sauté garlic and onion.\nAdd vegetables. Stir-fry on high heat 3–4 min.\nAdd soy sauce and oyster sauce. Toss well.\nReturn bangus. Mix gently.\nDrizzle sesame oil. Serve hot.",
    notes: "Per serving: 390 kcal · 12g carbs · 38g protein · 20g fat · 3g sugar · 480mg sodium\nPrep/cook time: 20 min",
  },
  {
    id: "low-carb-chicken-afritada-low-carb",
    category: "Low Carb",
    title: "Chicken Afritada (Low Carb)",
    yield_text: "1 serving",
    ingredients: "200g chicken breast, cubed\n½ cup tomato sauce\n¼ cup chicken broth\n½ bell pepper, sliced\n½ cup green peas\n2 cloves garlic\n½ onion\nFish sauce, salt & pepper\n1 tsp oil",
    procedure: "Sauté garlic and onion. Add chicken. Brown lightly.\nPour in tomato sauce and broth. Stir.\nSimmer covered 15 min.\nAdd bell pepper and green peas. Cook 5 more min.\nSeason with fish sauce, salt and pepper.\nServe with cauliflower rice.",
    notes: "Per serving: 360 kcal · 12g carbs · 42g protein · 14g fat · 4g sugar · 620mg sodium\nPrep/cook time: 35 min",
  },
  {
    id: "low-carb-egg-tofu-scramble",
    category: "Low Carb",
    title: "Egg & Tofu Scramble",
    yield_text: "1 serving",
    ingredients: "2 large eggs\n150g firm tofu, cubed\n2 cloves garlic, minced\n½ small onion, diced\n1 tbsp soy sauce\n1 tsp vinegar\n¼ tsp black pepper\nSpring onion\n1 tsp oil",
    procedure: "Pan-fry tofu until golden on all sides. Set aside.\nIn same pan, sauté garlic and onion.\nBeat eggs. Pour into pan. Scramble gently.\nAdd tofu back in. Mix together.\nSeason with soy sauce, vinegar, and pepper.\nTop with spring onion. Serve warm.",
    notes: "Per serving: 320 kcal · 6g carbs · 28g protein · 20g fat · 1g sugar · 310mg sodium\nPrep/cook time: 15 min",
  },
  {
    id: "low-carb-salmon-sinigang",
    category: "Low Carb",
    title: "Salmon Sinigang",
    yield_text: "1 serving",
    ingredients: "180g salmon fillet\n½ pack sinigang mix\n½ cup kangkong or spinach\n½ cup sitaw\n1 tomato, quartered\n½ onion, quartered\n2.5 cups water\nFish sauce & pepper to taste",
    procedure: "Boil water with onion and tomatoes 5 min.\nAdd sinigang mix. Stir to dissolve.\nAdd string beans. Cook 5 min.\nAdd salmon. Simmer gently 5–7 min until cooked.\nAdd kangkong last. Cook 1 min.\nSeason with fish sauce and pepper. Serve hot.",
    notes: "Per serving: 380 kcal · 10g carbs · 42g protein · 18g fat · 2g sugar · 790mg sodium\nPrep/cook time: 25 min",
  },
  {
    id: "carnivore-beef-tapa-fried-eggs",
    category: "Carnivore",
    title: "Beef Tapa & Fried Eggs",
    yield_text: "1 serving",
    ingredients: "200g beef sirloin, thinly sliced\n2 tbsp soy sauce\n1 tbsp vinegar\n½ tsp garlic powder\n½ tsp sugar substitute\n2 eggs\n1 tbsp butter",
    procedure: "Mix soy sauce, vinegar, garlic powder, sugar sub. Marinate beef 15 min.\nPan-fry beef on high in butter 2–3 min per side until browned.\nIn same pan, fry eggs sunny side up.\nPlate tapa alongside eggs.\nPour any pan juices over beef.\nServe immediately while hot.",
    notes: "Per serving: 580 kcal · 2g carbs · 50g protein · 40g fat · 5g sugar · 780mg sodium\nPrep/cook time: 20 min",
  },
  {
    id: "carnivore-pork-belly-lechon-kawali",
    category: "Carnivore",
    title: "Pork Belly Lechon Kawali",
    yield_text: "1 serving",
    ingredients: "200g pork belly slab\n½ tsp salt\n¼ tsp black pepper\n½ tsp garlic powder\n1 bay leaf\nWater to boil\nOil for frying",
    procedure: "Boil pork belly with salt, pepper, garlic powder, bay leaf 25 min.\nRemove. Pat bone-dry. Rest 15 min.\nDeep fry at 180°C for 12–15 min until super crispy.\nAlternatively air-fry at 210°C for 18 min.\nRest 5 min. Chop into thick pieces.\nServe with soy-vinegar dipping sauce.",
    notes: "Per serving: 680 kcal · 0g carbs · 32g protein · 60g fat\nPrep/cook time: 50 min",
  },
  {
    id: "carnivore-beef-bulalo-pure-carnivore",
    category: "Carnivore",
    title: "Beef Bulalo (Pure Carnivore)",
    yield_text: "1 serving",
    ingredients: "350g beef shank with bone\n2 cups water\n½ tsp salt\n½ tsp black pepper\nBone marrow from the bone",
    procedure: "Blanch beef shank in boiling water 5 min. Drain and rinse.\nTransfer to fresh pot. Cover with water.\nBring to a boil. Skim foam.\nSimmer on low 75–90 min until very tender.\nSeason with salt and pepper only.\nServe with bone marrow scooped onto the meat.",
    notes: "Per serving: 520 kcal · 0g carbs · 48g protein · 36g fat · 0g sugar · 420mg sodium\nPrep/cook time: 90 min",
  },
  {
    id: "carnivore-pork-bbq-skewers-inihaw-na-baboy",
    category: "Carnivore",
    title: "Pork BBQ Skewers (Inihaw na Baboy)",
    yield_text: "1 serving",
    ingredients: "250g pork shoulder or belly, cubed\n2 tbsp soy sauce\n1 tbsp vinegar\n½ tsp garlic powder\n½ tsp black pepper\n¼ tsp salt\n1 tbsp butter for basting",
    procedure: "Mix soy sauce, vinegar, garlic powder, pepper, salt. Marinate pork 20 min.\nThread onto skewers.\nGrill over charcoal or pan-grill on high heat.\nBaste with butter every 2 min while grilling.\nCook 10–12 min total, turning frequently.\nServe hot off the grill.",
    notes: "Per serving: 480 kcal · 2g carbs · 38g protein · 36g fat · 8g sugar · 680mg sodium\nPrep/cook time: 30 min",
  },
  {
    id: "carnivore-chicken-inasal-grilled-chicken",
    category: "Carnivore",
    title: "Chicken Inasal (Grilled Chicken)",
    yield_text: "1 serving",
    ingredients: "2 chicken thighs or 1 leg quarter\n2 tbsp soy sauce\n1 tbsp vinegar\n3 calamansi, juiced\n½ thumb ginger, grated\n2 cloves garlic, minced\n½ tsp black pepper\n1 tbsp butter for basting",
    procedure: "Mix soy sauce, vinegar, calamansi, ginger, garlic, pepper. Marinate chicken 20 min.\nHeat grill to high.\nGrill chicken 8–10 min per side.\nBaste with butter every few minutes.\nCook until charred and cooked through.\nRest 5 min before serving.",
    notes: "Per serving: 440 kcal · 2g carbs · 50g protein · 24g fat · 2g sugar · 490mg sodium\nPrep/cook time: 35 min",
  },
  {
    id: "carnivore-scrambled-eggs-with-bacon-liver",
    category: "Carnivore",
    title: "Scrambled Eggs with Bacon & Liver",
    yield_text: "1 serving",
    ingredients: "2 strips bacon, chopped\n100g chicken liver, cleaned\n2 eggs, beaten\n2 cloves garlic, minced\n1 tbsp butter\nSalt & pepper",
    procedure: "Cook bacon in butter until crispy. Set aside.\nAdd garlic. Sauté 30 sec.\nAdd chicken liver. Cook 3–4 min per side until no longer pink.\nPush liver to side. Pour in eggs.\nScramble gently, mixing with liver as it sets.\nAdd bacon back in. Season and serve hot.",
    notes: "Per serving: 500 kcal · 2g carbs · 42g protein · 36g fat · 0g sugar · 610mg sodium\nPrep/cook time: 15 min",
  },
  {
    id: "clean-eating-brown-rice-chicken-bowl",
    category: "Clean Eating",
    title: "Brown Rice Chicken Bowl",
    yield_text: "1 serving",
    ingredients: "150g chicken breast, sliced\n1 cup cooked brown rice (~180g)\n1 cup kangkong or pechay, chopped\n2 cloves garlic\n½ onion\n1 tbsp soy sauce (low sodium)\n1 tsp calamansi juice\n1 tsp sesame oil\nSalt & pepper\n1 tsp oil",
    procedure: "Sauté garlic and onion in oil.\nAdd chicken. Cook until done. Season with soy sauce and calamansi.\nAdd kangkong. Cook 2 min until wilted.\nDrizzle sesame oil. Season to taste.\nServe over brown rice.\nKeep portions measured for best results.",
    notes: "Per serving: 450 kcal · 46g carbs · 40g protein · 10g fat · 1g sugar · 520mg sodium\nPrep/cook time: 25 min",
  },
  {
    id: "clean-eating-pinakbet-clean-version",
    category: "Clean Eating",
    title: "Pinakbet (Clean Version)",
    yield_text: "1 serving",
    ingredients: "100g lean pork, small cubes\n½ cup squash (kalabasa), cubed\n½ cup eggplant, sliced\n½ cup ampalaya, sliced\n½ cup okra\n½ cup sitaw\n2 tbsp bagoong\n2 cloves garlic\n½ onion\n1 tomato\n¼ cup water\n1 tsp oil",
    procedure: "Sauté garlic, onion, tomatoes in oil.\nAdd pork. Cook until no longer pink.\nAdd bagoong. Stir 1 min.\nAdd squash and water. Cover, cook 5 min.\nAdd remaining vegetables. Cook covered 8 min.\nDo not over-stir. Serve hot.",
    notes: "Per serving: 290 kcal · 18g carbs · 20g protein · 14g fat · 3g sugar · 460mg sodium\nPrep/cook time: 25 min",
  },
  {
    id: "clean-eating-lentil-vegetable-sinigang",
    category: "Clean Eating",
    title: "Lentil & Vegetable Sinigang",
    yield_text: "1 serving",
    ingredients: "½ cup red lentils\n½ pack sinigang mix\n½ cup sitaw\n½ cup kangkong\n1 tomato, quartered\n½ onion, quartered\n2.5 cups water\nFish sauce or salt to taste",
    procedure: "Boil water with tomatoes and onion 5 min.\nAdd lentils. Cook 12 min until soft.\nStir in sinigang mix.\nAdd string beans. Cook 5 min.\nAdd kangkong last. Cook 1 min.\nSeason with fish sauce. Serve hot.",
    notes: "Per serving: 340 kcal · 48g carbs · 20g protein · 6g fat · 3g sugar · 580mg sodium\nPrep/cook time: 30 min",
  },
  {
    id: "clean-eating-steamed-tilapia-with-ginger",
    category: "Clean Eating",
    title: "Steamed Tilapia with Ginger",
    yield_text: "1 serving",
    ingredients: "200g tilapia fillet\n½ thumb ginger, julienned\n2 cloves garlic, sliced\n1 spring onion\n1 tbsp soy sauce (low sodium)\n1 tsp sesame oil\n1 tsp calamansi juice\nChili (optional)",
    procedure: "Season fish lightly with salt.\nPlace on steaming plate. Top with ginger, garlic, spring onion.\nMix soy sauce, sesame oil, calamansi. Pour over fish.\nSteam over boiling water 12–15 min until cooked through.\nGarnish with more spring onion.\nServe with ½ cup brown rice (+160 kcal if added).",
    notes: "Per serving: 300 kcal · 4g carbs · 44g protein · 10g fat · 0g sugar · 280mg sodium\nPrep/cook time: 25 min",
  },
  {
    id: "clean-eating-mongo-soup-clean",
    category: "Clean Eating",
    title: "Mongo Soup (Clean)",
    yield_text: "1 serving",
    ingredients: "½ cup mung beans, washed\n100g lean pork or bangus tinapa\n½ cup malunggay leaves\n2 cloves garlic\n½ onion\n1 tomato\n2.5 cups water\nFish sauce & pepper\n1 tsp oil",
    procedure: "Boil mung beans in water until soft, about 25 min.\nSauté garlic, onion, tomatoes.\nAdd pork or flaked tinapa. Cook 3 min.\nPour sautéed mixture into mung beans.\nSimmer 5 more min. Season.\nAdd malunggay last. Cook 1 min. Serve hot.",
    notes: "Per serving: 360 kcal · 44g carbs · 22g protein · 10g fat · 2g sugar · 390mg sodium\nPrep/cook time: 35 min",
  },
  {
    id: "clean-eating-overnight-oats-with-mango-chia",
    category: "Clean Eating",
    title: "Overnight Oats with Mango & Chia",
    yield_text: "1 serving",
    ingredients: "½ cup rolled oats\n¾ cup low-fat milk\n2 tbsp chia seeds\n1 tsp honey\n½ ripe mango, diced\nPinch of cinnamon",
    procedure: "Add oats and chia seeds to a jar.\nPour in milk. Stir well.\nAdd honey and cinnamon. Mix again.\nCover and refrigerate overnight (at least 6 hours).\nIn the morning, top with fresh diced mango.\nStir before eating. Add more milk if too thick.",
    notes: "Per serving: 380 kcal · 52g carbs · 14g protein · 12g fat · 18g sugar · 85mg sodium\nPrep/cook time: 5 min (overnight)",
  },
  {
    id: "if-only-break-fast-arroz-caldo",
    category: "IF Only",
    title: "Break-Fast Arroz Caldo",
    yield_text: "1 serving",
    ingredients: "150g chicken, shredded\n½ cup white rice\n½ thumb ginger, julienned\n2 cloves garlic, minced\n½ onion, diced\n2 cups chicken broth\nFish sauce to taste\n1 boiled egg, spring onion, calamansi\n1 tsp oil",
    procedure: "Sauté garlic, onion, ginger in oil.\nAdd chicken. Stir 2 min.\nAdd rice and broth. Bring to a boil.\nSimmer 18–20 min, stirring often, until porridge consistency.\nSeason with fish sauce.\nServe with boiled egg, spring onion, and calamansi. Ideal first meal after fasting.",
    notes: "Per serving: 420 kcal · 44g carbs · 32g protein · 12g fat · 1g sugar · 560mg sodium\nPrep/cook time: 25 min",
  },
  {
    id: "if-only-banana-peanut-butter-oats",
    category: "IF Only",
    title: "Banana & Peanut Butter Oats",
    yield_text: "1 serving",
    ingredients: "½ cup rolled oats\n1 cup water or milk\n1 small banana, sliced\n2 tbsp natural peanut butter\n1 tsp honey\nPinch of salt",
    procedure: "Cook oats in water or milk over medium heat 5 min, stirring.\nRemove from heat. Pinch of salt.\nTransfer to a bowl.\nTop with banana slices.\nDollop peanut butter on top. Drizzle honey.\nEat as your first meal after fasting.",
    notes: "Per serving: 430 kcal · 56g carbs · 14g protein · 16g fat · 16g sugar · 130mg sodium\nPrep/cook time: 10 min",
  },
  {
    id: "if-only-egg-malunggay-soup",
    category: "IF Only",
    title: "Egg & Malunggay Soup",
    yield_text: "1 serving",
    ingredients: "2 eggs\n1 cup malunggay leaves\n2 cups chicken broth\n2 cloves garlic, minced\nSalt & pepper\n1 tsp oil",
    procedure: "Heat broth in a pot. Bring to a gentle simmer.\nSauté garlic in oil. Add to broth.\nBeat eggs. Slowly drizzle into simmering broth while stirring.\nAdd malunggay leaves. Cook 1 min.\nSeason with salt and pepper.\nServe hot — ideal light break-fast after fasting.",
    notes: "Per serving: 240 kcal · 4g carbs · 20g protein · 15g fat · 1g sugar · 390mg sodium\nPrep/cook time: 10 min",
  },
  {
    id: "if-only-silog-plate-eating-window",
    category: "IF Only",
    title: "Silog Plate (Eating Window)",
    yield_text: "1 serving",
    ingredients: "150g tapa or tocino\n1 cup sinangag (garlic fried rice, ~180g cooked)\n2 eggs\n2 cloves garlic for rice\n1 cup day-old rice\n1 tbsp oil\nVinegar dipping sauce",
    procedure: "Heat oil. Sauté garlic until golden. Add rice. Stir-fry until separated and fragrant.\nIn separate pan, cook tapa or tocino.\nFry eggs sunny-side up.\nPlate rice, then protein, then eggs.\nServe with cane vinegar and crushed garlic.\nBest eaten during eating window to fuel active hours.",
    notes: "Per serving: 750 kcal · 46g carbs · 36g protein · 44g fat · 5g sugar · 890mg sodium\nPrep/cook time: 20 min",
  },
  {
    id: "if-only-chicken-sopas",
    category: "IF Only",
    title: "Chicken Sopas",
    yield_text: "1 serving",
    ingredients: "150g chicken breast, shredded\n½ cup elbow macaroni\n½ cup cabbage, shredded\n¼ cup carrots, diced\n3 tbsp evaporated milk\n2 cups chicken broth\n½ onion, diced\n2 cloves garlic\nSalt & pepper\n1 tsp oil",
    procedure: "Sauté garlic and onion in oil.\nAdd chicken. Stir 2 min.\nPour in broth. Bring to a boil.\nAdd macaroni. Cook 8–10 min.\nAdd cabbage and carrots. Cook 5 min.\nStir in milk. Season. Simmer 2 more min. Serve hot.",
    notes: "Per serving: 420 kcal · 38g carbs · 32g protein · 14g fat · 2g sugar · 610mg sodium\nPrep/cook time: 30 min",
  },
  {
    id: "if-only-salmon-rice-bowl-end-of-window",
    category: "IF Only",
    title: "Salmon & Rice Bowl (End-of-Window)",
    yield_text: "1 serving",
    ingredients: "180g salmon fillet\n1 cup cooked rice (~180g)\n1 cup kangkong, blanched\n2 calamansi, juiced\n2 tbsp soy sauce\n1 tsp sesame oil\n2 cloves garlic\n1 tbsp oil",
    procedure: "Season salmon with salt and pepper. Pan-fry in oil 4 min per side.\nMix calamansi juice, soy sauce, sesame oil for dressing.\nBlanch kangkong 1 min. Drain.\nSauté garlic briefly. Toss with kangkong.\nPlate rice, flaked salmon, and kangkong.\nDrizzle dressing. Best as last meal before fasting window starts.",
    notes: "Per serving: 520 kcal · 46g carbs · 42g protein · 16g fat · 1g sugar · 380mg sodium\nPrep/cook time: 20 min",
  },
  {
    id: "pescatarian-sinigang-na-salmon",
    category: "Pescatarian",
    title: "Sinigang na Salmon",
    yield_text: "1 serving",
    ingredients: "200g salmon belly or fillet\n½ pack sinigang mix\n½ cup kangkong\n½ cup sitaw\n1 tomato, quartered\n½ onion, quartered\n½ cup radish, sliced\n2.5 cups water\nFish sauce to taste",
    procedure: "Boil water. Add onion, tomatoes, radish. Simmer 8 min.\nAdd sinigang mix. Stir.\nAdd salmon. Cook 5–7 min — do not overcook.\nAdd string beans. Cook 3 min.\nAdd kangkong last. Cook 1 min.\nSeason with fish sauce. Serve hot.",
    notes: "Per serving: 400 kcal · 10g carbs · 42g protein · 20g fat · 2g sugar · 820mg sodium\nPrep/cook time: 25 min",
  },
  {
    id: "pescatarian-pinangat-na-isda",
    category: "Pescatarian",
    title: "Pinangat na Isda",
    yield_text: "1 serving",
    ingredients: "200g tilapia or bangus fillet\n2 cloves garlic, minced\n½ thumb ginger, julienned\n1 tomato, sliced\n½ cup taro leaves or kangkong\n2 calamansi, juiced\n1 tbsp fish sauce\nSalt & pepper\nBanana leaf or foil",
    procedure: "Lay banana leaf or foil flat. Place taro leaves as base.\nLay fish on top. Season with salt and pepper.\nTop with garlic, ginger, tomatoes.\nDrizzle calamansi juice and fish sauce over fish.\nWrap tightly. Seal edges.\nSteam 20 min or bake at 190°C for 20 min. Serve in wrapping.",
    notes: "Per serving: 310 kcal · 6g carbs · 38g protein · 14g fat · 1g sugar · 490mg sodium\nPrep/cook time: 30 min",
  },
  {
    id: "pescatarian-shrimp-sitaw-stir-fry",
    category: "Pescatarian",
    title: "Shrimp & Sitaw Stir-Fry",
    yield_text: "1 serving",
    ingredients: "200g shrimp, peeled and deveined\n1 cup sitaw, cut 2-inch pieces\n3 cloves garlic, minced\n½ onion, sliced\n1 tbsp oyster sauce\n1 tbsp soy sauce\n1 tsp sesame oil\n1 tsp oil\nSalt & pepper",
    procedure: "Heat oil in wok over high heat.\nSauté garlic and onion 1 min.\nAdd shrimp. Stir-fry 2–3 min until pink.\nAdd sitaw. Stir-fry 3–4 min until tender-crisp.\nAdd oyster sauce and soy sauce. Toss to coat.\nDrizzle sesame oil. Serve immediately.",
    notes: "Per serving: 320 kcal · 12g carbs · 34g protein · 14g fat · 2g sugar · 720mg sodium\nPrep/cook time: 15 min",
  },
  {
    id: "pescatarian-bangus-belly-inihaw",
    category: "Pescatarian",
    title: "Bangus Belly Inihaw",
    yield_text: "1 serving",
    ingredients: "1 bangus belly cut (~250g)\n3 tbsp soy sauce\n2 calamansi, juiced\n2 cloves garlic, minced\n½ tsp black pepper\n1 tomato, diced\n¼ red onion, diced\nVinegar dipping sauce",
    procedure: "Mix soy sauce, calamansi juice, garlic, pepper.\nScore bangus. Marinate 15 min.\nGrill or broil 5–6 min per side until charred.\nMix tomato and red onion with splash of vinegar.\nPlate grilled bangus with tomato-onion salsa on top.\nServe with soy-vinegar dip.",
    notes: "Per serving: 420 kcal · 4g carbs · 38g protein · 28g fat · 0g sugar · 310mg sodium\nPrep/cook time: 25 min",
  },
  {
    id: "pescatarian-tofu-vegetable-kare-kare",
    category: "Pescatarian",
    title: "Tofu & Vegetable Kare-Kare",
    yield_text: "1 serving",
    ingredients: "150g firm tofu, cubed\n½ cup eggplant, sliced\n½ cup sitaw\n½ cup banana heart, sliced\n2 tbsp peanut butter (natural)\n½ cup vegetable broth\n½ tsp annatto powder\n½ onion\n2 cloves garlic\nBagoong to serve (1 tbsp)",
    procedure: "Dissolve annatto in ¼ cup warm broth.\nSauté garlic and onion until soft.\nAdd peanut butter and broth. Stir until smooth.\nAdd tofu and vegetables. Simmer 12–15 min.\nPour in annatto broth. Stir to colour.\nServe with a side of bagoong.",
    notes: "Per serving: 380 kcal · 20g carbs · 20g protein · 26g fat · 4g sugar · 540mg sodium\nPrep/cook time: 35 min",
  },
  {
    id: "pescatarian-tuna-sisig",
    category: "Pescatarian",
    title: "Tuna Sisig",
    yield_text: "1 serving",
    ingredients: "1 can tuna in oil (185g), drained\n¼ cup red onion, minced\n2 calamansi, juiced\n1 tbsp mayonnaise\n1 green chili, sliced\n1 tbsp soy sauce\n½ tsp black pepper\n1 tsp oil\n1 fried egg (optional, +90 kcal)",
    procedure: "Heat oil in pan until very hot.\nAdd tuna. Press down and sear 2–3 min without stirring.\nFlip sections. Sear other side 2 min.\nAdd onion, soy sauce, chili. Stir and cook 2 min.\nRemove from heat. Add mayo and calamansi. Toss.\nServe sizzling hot, topped with fried egg if desired.",
    notes: "Per serving: 380 kcal · 6g carbs · 38g protein · 22g fat · 1g sugar · 680mg sodium\nPrep/cook time: 20 min",
  },
  {
    id: "diabetic-friendly-brown-rice-arroz-caldo",
    category: "Diabetic-Friendly",
    title: "Brown Rice Arroz Caldo",
    yield_text: "1 serving",
    ingredients: "150g chicken breast, shredded\n½ cup brown rice\n½ thumb ginger, julienned\n2 cloves garlic, minced\n½ onion, diced\n2 cups low-sodium broth\nFish sauce (small amount)\n1 boiled egg, spring onion, calamansi",
    procedure: "Sauté garlic, onion, ginger in a little oil.\nAdd chicken. Cook 2 min.\nAdd brown rice and broth. Bring to a boil.\nReduce heat. Simmer 30–35 min until porridge-like, stirring often.\nSeason with fish sauce (use sparingly).\nTop with spring onion, boiled egg and calamansi. No sugar.",
    notes: "Per serving: 360 kcal · 40g carbs · 30g protein · 8g fat · 1g sugar · 590mg sodium\nPrep/cook time: 40 min",
  },
  {
    id: "diabetic-friendly-tilapia-ampalaya-stir-fry",
    category: "Diabetic-Friendly",
    title: "Tilapia & Ampalaya Stir-Fry",
    yield_text: "1 serving",
    ingredients: "200g tilapia fillet, cubed\n1 cup ampalaya, sliced thin\n2 cloves garlic\n½ onion\n1 egg, beaten\n1 tbsp soy sauce (low sodium)\nSalt & pepper\n1 tsp oil",
    procedure: "Rub ampalaya with salt. Sit 5 min. Squeeze and rinse.\nPan-fry tilapia until golden. Set aside.\nSauté garlic and onion. Add ampalaya. Stir-fry 3 min.\nPush to side. Add egg. Scramble lightly.\nAdd tilapia back. Season with soy sauce and pepper.\nMix gently. Serve hot.",
    notes: "Per serving: 290 kcal · 8g carbs · 38g protein · 10g fat · 3g sugar · 490mg sodium\nPrep/cook time: 20 min",
  },
  {
    id: "diabetic-friendly-chicken-vegetable-sinigang",
    category: "Diabetic-Friendly",
    title: "Chicken & Vegetable Sinigang",
    yield_text: "1 serving",
    ingredients: "200g chicken breast\n½ pack low-sodium sinigang mix\n½ cup kangkong\n½ cup sitaw\n½ cup radish, sliced\n1 tomato\n½ onion\n2.5 cups water\nMinimal fish sauce",
    procedure: "Boil water. Add onion, tomatoes, radish.\nAdd chicken. Simmer 15 min.\nStir in sinigang mix (use half pack to control sodium).\nAdd sitaw. Cook 5 min.\nAdd kangkong. Cook 1 min.\nSeason minimally. Low-GI and blood sugar friendly.",
    notes: "Per serving: 300 kcal · 12g carbs · 38g protein · 8g fat · 2g sugar · 810mg sodium\nPrep/cook time: 30 min",
  },
  {
    id: "diabetic-friendly-mongo-soup-diabetic-friendly",
    category: "Diabetic-Friendly",
    title: "Mongo Soup (Diabetic-Friendly)",
    yield_text: "1 serving",
    ingredients: "½ cup mung beans, washed\n80g lean pork (optional)\n½ cup malunggay or spinach\n2 cloves garlic\n½ onion\n1 tomato\n2.5 cups water\nFish sauce & pepper\n1 tsp oil",
    procedure: "Boil mung beans in water 25 min until soft.\nSauté garlic, onion, tomatoes. Add pork. Cook 5 min.\nAdd sautéed mix to mung beans. Simmer 5 min.\nSeason lightly.\nAdd malunggay. Cook 1 min.\nMung beans are low-GI — excellent for blood sugar control.",
    notes: "Per serving: 320 kcal · 42g carbs · 20g protein · 6g fat · 2g sugar · 280mg sodium\nPrep/cook time: 35 min",
  },
  {
    id: "diabetic-friendly-baked-chicken-with-roasted-vegetables",
    category: "Diabetic-Friendly",
    title: "Baked Chicken with Roasted Vegetables",
    yield_text: "1 serving",
    ingredients: "200g chicken thigh, skin removed\n1 cup broccoli florets\n½ cup carrots, sliced\n½ cup sayote, cubed\n2 cloves garlic, minced\n1 tbsp olive oil\n½ tsp paprika\n½ tsp dried oregano\nSalt & pepper",
    procedure: "Preheat oven to 200°C.\nMix olive oil, garlic, paprika, oregano, salt, pepper.\nRub over skinless chicken.\nToss vegetables in remaining oil mix. Spread on baking tray.\nPlace chicken on top of vegetables.\nBake 30–35 min until chicken is cooked and vegetables tender.",
    notes: "Per serving: 360 kcal · 14g carbs · 42g protein · 14g fat · 5g sugar · 390mg sodium\nPrep/cook time: 40 min",
  },
  {
    id: "diabetic-friendly-egg-malunggay-omelette",
    category: "Diabetic-Friendly",
    title: "Egg & Malunggay Omelette",
    yield_text: "1 serving",
    ingredients: "3 eggs\n½ cup malunggay leaves\n2 cloves garlic, minced\n¼ onion, minced\n1 tomato, diced\nSalt & pepper\n1 tsp oil",
    procedure: "Beat eggs with a pinch of salt and pepper.\nHeat oil. Sauté garlic, onion, tomato 2 min.\nAdd malunggay. Stir 30 sec.\nPour eggs over mixture. Do not stir.\nLet set 1 min. Fold in half.\nCook 1 more min. Serve. Malunggay helps blood sugar regulation.",
    notes: "Per serving: 240 kcal · 4g carbs · 20g protein · 16g fat · 1g sugar · 280mg sodium\nPrep/cook time: 10 min",
  },
  {
    id: "low-sodium-steamed-bangus-with-ginger-calamansi",
    category: "Low Sodium",
    title: "Steamed Bangus with Ginger & Calamansi",
    yield_text: "1 serving",
    ingredients: "200g bangus fillet\n½ thumb ginger, julienned\n2 calamansi, juiced\n2 cloves garlic, sliced\n1 spring onion\n1 tsp sesame oil\nTiny pinch of salt",
    procedure: "Score bangus fillet lightly.\nPlace on steaming plate. Top with ginger and garlic.\nDrizzle calamansi juice and sesame oil.\nSteam over boiling water 12–15 min.\nGarnish with sliced spring onion.\nServe with no dipping sauce — natural flavour is the point.",
    notes: "Per serving: 300 kcal · 4g carbs · 38g protein · 14g fat · 0g sugar · 240mg sodium\nPrep/cook time: 20 min",
  },
  {
    id: "low-sodium-no-salt-chicken-tinola",
    category: "Low Sodium",
    title: "No-Salt Chicken Tinola",
    yield_text: "1 serving",
    ingredients: "200g chicken thigh, bone-in\n½ thumb ginger, sliced\n2 cloves garlic\n½ onion\n1 cup sayote, cubed\n½ cup malunggay leaves\n1.5 cups unsalted broth\nPepper only\n1 tsp oil",
    procedure: "Sauté garlic, onion, ginger in oil.\nAdd chicken. Brown slightly.\nPour in unsalted broth. Boil.\nSimmer 15 min. Add sayote. Cook 5 more min.\nAdd malunggay last. Cook 1 min.\nSeason with pepper only. Squeeze calamansi for brightness.",
    notes: "Per serving: 290 kcal · 6g carbs · 40g protein · 10g fat · 1g sugar · 95mg sodium\nPrep/cook time: 30 min",
  },
  {
    id: "low-sodium-lemon-herb-grilled-chicken",
    category: "Low Sodium",
    title: "Lemon Herb Grilled Chicken",
    yield_text: "1 serving",
    ingredients: "200g chicken breast\n2 calamansi, juiced\n½ tsp dried oregano\n½ tsp garlic powder\n¼ tsp paprika\n¼ tsp black pepper\n1 tbsp olive oil\nNo salt",
    procedure: "Mix calamansi juice, oregano, garlic powder, paprika, pepper and olive oil.\nCoat chicken. Marinate 15 min.\nGrill on high heat 6–7 min per side until charred.\nRest 5 min before slicing.\nServe with steamed vegetables.\nThe herbs and calamansi replace salt completely.",
    notes: "Per serving: 320 kcal · 2g carbs · 46g protein · 14g fat · 0g sugar · 310mg sodium\nPrep/cook time: 25 min",
  },
  {
    id: "low-sodium-vegetable-mongo-soup-unsalted",
    category: "Low Sodium",
    title: "Vegetable Mongo Soup (Unsalted)",
    yield_text: "1 serving",
    ingredients: "½ cup mung beans\n½ cup malunggay or spinach\n½ cup squash, cubed\n1 tomato, quartered\n½ onion\n2 cloves garlic\n2.5 cups water\nPepper & calamansi only",
    procedure: "Boil mung beans 25 min until soft.\nSauté garlic, onion, tomatoes in a little oil.\nAdd squash. Cook 3 min.\nAdd sautéed mix to mung beans. Simmer 5 min.\nAdd malunggay or spinach. Cook 1 min.\nSeason with pepper and calamansi only. No salt.",
    notes: "Per serving: 300 kcal · 44g carbs · 16g protein · 6g fat · 2g sugar · 85mg sodium\nPrep/cook time: 35 min",
  },
  {
    id: "low-sodium-egg-white-malunggay-scramble",
    category: "Low Sodium",
    title: "Egg White & Malunggay Scramble",
    yield_text: "1 serving",
    ingredients: "3 egg whites + 1 whole egg\n1 cup malunggay leaves\n½ tomato, diced\n2 cloves garlic, minced\n¼ onion, minced\n1 tsp olive oil\nBlack pepper only",
    procedure: "Beat egg whites and whole egg together.\nHeat olive oil. Sauté garlic, onion, tomato 2 min.\nAdd malunggay. Stir 30 sec.\nPour in eggs. Scramble over low heat until just set.\nSeason with black pepper only.\nNo salt at all — naturally light and clean.",
    notes: "Per serving: 200 kcal · 4g carbs · 22g protein · 10g fat · 0g sugar · 190mg sodium\nPrep/cook time: 10 min",
  },
  {
    id: "low-sodium-herb-roasted-sweet-potato-tuna",
    category: "Low Sodium",
    title: "Herb-Roasted Sweet Potato & Tuna",
    yield_text: "1 serving",
    ingredients: "1 medium camote (~150g), cubed\n1 can tuna in water (185g, no salt), drained\n½ tsp garlic powder\n½ tsp dried rosemary or oregano\n¼ tsp black pepper\n1 tbsp olive oil\nCalamansi juice to finish",
    procedure: "Preheat oven to 200°C.\nToss camote with olive oil, garlic powder, oregano, pepper.\nRoast 22–25 min until tender.\nWhile hot, flake tuna into roasted camote.\nToss gently. Squeeze calamansi over top.\nServe warm — no salt needed.",
    notes: "Per serving: 350 kcal · 34g carbs · 32g protein · 8g fat · 5g sugar · 320mg sodium\nPrep/cook time: 30 min",
  },
  {
    id: "calorie-deficit-chicken-breast-sinangag",
    category: "Calorie Deficit",
    title: "Chicken Breast Sinangag",
    yield_text: "1 serving",
    ingredients: "150g chicken breast, grilled and sliced\n1 cup day-old rice (~180g)\n3 cloves garlic, minced\n1 egg\n1 tbsp soy sauce\n1 tsp sesame oil\nSpring onion\n1 tsp oil",
    procedure: "Heat oil. Sauté garlic until golden.\nAdd rice. Stir-fry until separated and fragrant.\nPush to side. Crack in egg. Scramble and mix through rice.\nAdd soy sauce and sesame oil. Toss.\nPlate rice and top with sliced grilled chicken.\nGarnish with spring onion. A satisfying deficit-friendly meal.",
    notes: "Per serving: 400 kcal · 38g carbs · 38g protein · 10g fat · 0g sugar · 380mg sodium\nPrep/cook time: 20 min",
  },
  {
    id: "calorie-deficit-tinolang-manok-light",
    category: "Calorie Deficit",
    title: "Tinolang Manok (Light)",
    yield_text: "1 serving",
    ingredients: "180g chicken breast\n½ thumb ginger\n2 cloves garlic\n½ onion\n1 cup sayote, cubed\n½ cup malunggay\n1.5 cups broth\nFish sauce & pepper\n1 tsp oil",
    procedure: "Sauté garlic, onion, ginger.\nAdd chicken. Brown lightly.\nAdd broth. Simmer 15 min.\nAdd sayote. Cook 5 min.\nAdd malunggay. Cook 1 min.\nSeason lightly. Low calorie, very filling.",
    notes: "Per serving: 280 kcal · 6g carbs · 36g protein · 10g fat · 1g sugar · 420mg sodium\nPrep/cook time: 30 min",
  },
  {
    id: "calorie-deficit-egg-white-omelette-with-vegetables",
    category: "Calorie Deficit",
    title: "Egg White Omelette with Vegetables",
    yield_text: "1 serving",
    ingredients: "4 egg whites\n1 whole egg\n½ cup mixed vegetables (bell pepper, onion, tomato)\n2 cloves garlic\nSalt & pepper\n1 tsp oil",
    procedure: "Beat egg whites and whole egg together. Season.\nHeat oil. Sauté garlic and vegetables 2 min.\nPour eggs over vegetables.\nLet set 1 min. Fold in half.\nCook 1 more min until done.\nHigh protein, low calorie — perfect for a deficit day.",
    notes: "Per serving: 200 kcal · 8g carbs · 22g protein · 8g fat · 2g sugar · 230mg sodium\nPrep/cook time: 10 min",
  },
  {
    id: "calorie-deficit-tuna-kangkong-rice-bowl",
    category: "Calorie Deficit",
    title: "Tuna & Kangkong Rice Bowl",
    yield_text: "1 serving",
    ingredients: "1 can tuna in water (185g), drained\n1 cup cooked rice (~180g)\n1 cup kangkong, blanched\n2 cloves garlic\n1 tbsp soy sauce\n1 tsp sesame oil\n1 tsp oil\nCalamansi to serve",
    procedure: "Drain tuna well.\nBlanch kangkong 1 min. Drain.\nSauté garlic in oil. Add kangkong. Toss with soy sauce and sesame oil.\nHeat tuna briefly in pan.\nPlate rice, tuna, and kangkong.\nSqueeze calamansi over everything. Simple and filling.",
    notes: "Per serving: 380 kcal · 40g carbs · 36g protein · 8g fat · 1g sugar · 480mg sodium\nPrep/cook time: 15 min",
  },
  {
    id: "calorie-deficit-shrimp-vegetable-soup",
    category: "Calorie Deficit",
    title: "Shrimp & Vegetable Soup",
    yield_text: "1 serving",
    ingredients: "200g shrimp, peeled\n1 cup mixed vegetables (sayote, carrots, sitaw)\n2 cloves garlic\n½ onion\n2 cups broth\n1 tbsp fish sauce\nPepper\n1 tsp oil",
    procedure: "Sauté garlic and onion in oil.\nAdd vegetables. Stir-fry 2 min.\nPour in broth. Bring to boil.\nAdd shrimp. Cook 3–4 min until pink.\nSeason with fish sauce and pepper.\nVery low calorie, high protein — great for deficit days.",
    notes: "Per serving: 240 kcal · 10g carbs · 30g protein · 8g fat · 2g sugar · 680mg sodium\nPrep/cook time: 20 min",
  },
  {
    id: "calorie-deficit-chicken-brown-rice-porridge",
    category: "Calorie Deficit",
    title: "Chicken & Brown Rice Porridge",
    yield_text: "1 serving",
    ingredients: "120g chicken breast, shredded\n½ cup brown rice\n2 cups low-sodium broth\n½ thumb ginger\n2 cloves garlic\n½ onion\nFish sauce (minimal)\nSpring onion & calamansi",
    procedure: "Sauté garlic, onion, ginger.\nAdd chicken. Stir 2 min.\nAdd brown rice and broth. Bring to boil.\nSimmer 30 min until porridge consistency.\nSeason sparingly with fish sauce.\nTop with spring onion and calamansi. Filling and light.",
    notes: "Per serving: 350 kcal · 42g carbs · 30g protein · 6g fat · 1g sugar · 490mg sodium\nPrep/cook time: 35 min",
  },
  {
    id: "ttc-folate-rich-spinach-egg-bowl",
    category: "TTC",
    title: "Folate-Rich Spinach & Egg Bowl",
    yield_text: "1 serving",
    ingredients: "2 large eggs\n2 cups fresh spinach\nCherry tomatoes\n1 clove garlic\n1 tbsp olive oil\n1 tbsp pumpkin seeds",
    procedure: "Saute garlic in olive oil 30s.\nAdd spinach, wilt 2 min.\nFry eggs alongside.\nTop with tomatoes and pumpkin seeds.",
    notes: "Per serving: 320 kcal · 18g carbs · 22g protein · 18g fat · 3g sugar · 280mg sodium\nPrep/cook time: 15 min",
  },
  {
    id: "ttc-salmon-avocado-fertility-bowl",
    category: "TTC",
    title: "Salmon & Avocado Fertility Bowl",
    yield_text: "1 serving",
    ingredients: "150g salmon fillet\n1/2 avocado sliced\n1/2 cup brown rice\n1 cup edamame\n1 tbsp sesame seeds\nCalamansi\nLow-sodium soy sauce",
    procedure: "Cook brown rice.\nGrill salmon with calamansi 4 min per side.\nAssemble bowl.\nTop with sesame seeds.",
    notes: "Per serving: 480 kcal · 22g carbs · 35g protein · 28g fat · 2g sugar · 320mg sodium\nPrep/cook time: 20 min",
  },
  {
    id: "ttc-lentil-malunggay-soup",
    category: "TTC",
    title: "Lentil & Malunggay Soup",
    yield_text: "2 servings",
    ingredients: "1 cup red lentils\n2 cups malunggay leaves\n1 carrot diced\n1 onion\n2 cloves garlic\n1 tsp turmeric\n4 cups low-sodium broth\n1 tbsp olive oil",
    procedure: "Saute onion and garlic.\nAdd carrot and turmeric, 2 min.\nAdd lentils and broth, simmer 20 min.\nStir in malunggay last 2 min.",
    notes: "Per serving: 290 kcal · 38g carbs · 18g protein · 7g fat · 4g sugar · 380mg sodium\nPrep/cook time: 30 min",
  },
  {
    id: "ttc-iron-boost-beef-kangkong",
    category: "TTC",
    title: "Iron-Boost Beef & Kangkong",
    yield_text: "1 serving",
    ingredients: "150g lean beef strips\n2 cups kangkong\n3 cloves garlic\n1 tbsp oyster sauce\n1 tsp sesame oil\nBlack sesame seeds",
    procedure: "Marinate beef in oyster sauce 10 min.\nStir-fry beef 3-4 min.\nAdd garlic and kangkong.\nFinish with sesame oil and sesame seeds.",
    notes: "Per serving: 380 kcal · 12g carbs · 32g protein · 22g fat · 2g sugar · 420mg sodium\nPrep/cook time: 20 min",
  },
  {
    id: "ttc-omega-3-bangus-with-quinoa",
    category: "TTC",
    title: "Omega-3 Bangus with Quinoa",
    yield_text: "1 serving",
    ingredients: "1 bangus fillet 200g\n1/2 cup quinoa\n1 cup broccoli\nCalamansi juice\n2 cloves garlic\n1 tbsp olive oil",
    procedure: "Cook quinoa.\nSeason bangus with calamansi and garlic.\nPan-fry bangus 12 min.\nSteam broccoli 5 min. Plate together.",
    notes: "Per serving: 440 kcal · 35g carbs · 38g protein · 16g fat · 1g sugar · 290mg sodium\nPrep/cook time: 25 min",
  },
  {
    id: "ttc-berry-oat-smoothie-bowl",
    category: "TTC",
    title: "Berry Oat Smoothie Bowl",
    yield_text: "1 serving",
    ingredients: "1/2 cup rolled oats\n1 cup mixed berries\n1 banana\n1 cup oat milk\n1 tbsp chia seeds\n1 tbsp honey",
    procedure: "Blend oats, berries, banana and milk.\nPour into bowl.\nTop with chia seeds and honey.",
    notes: "Per serving: 310 kcal · 52g carbs · 12g protein · 8g fat · 22g sugar · 85mg sodium\nPrep/cook time: 10 min",
  },
]
