// Preloaded grocery lists per diet mode — sourced from the CaloRhythm app
// (fasting mode excluded). Static app data; checked state is tracked
// per-user in the grocery_checks table.

export const GROCERY = {
  "Keto": [
    "Bacon strips",
    "Eggs (×12)",
    "Cauliflower (head)",
    "Garlic",
    "Butter",
    "Chicken thighs (bone-in)",
    "Sayote (chayote)",
    "Malunggay leaves",
    "Chicken broth",
    "Canned tuna in oil",
    "Avocado (ripe)",
    "Mayonnaise",
    "Calamansi (×10)",
    "Pork belly (slab)",
    "Ground pork or beef",
    "Iceberg lettuce",
    "Salmon fillets",
    "Spring onion",
    "Fish sauce",
    "Cooking oil"
  ],
  "Low Carb": [
    "Chicken breast",
    "Cauliflower rice (or head)",
    "Ginger",
    "Garlic",
    "Onion",
    "Pork belly slices (liempo)",
    "Soy sauce",
    "Green papaya (for atchara)",
    "Bangus (boneless fillet)",
    "Sitaw (string beans)",
    "Bell pepper",
    "Carrots",
    "Eggs",
    "Firm tofu (tokwa)",
    "Vinegar",
    "Oyster sauce",
    "Sesame oil",
    "Salmon fillet",
    "Kangkong (water spinach)",
    "Sinigang mix",
    "Calamansi"
  ],
  "Carnivore": [
    "Beef sirloin or flank (tapa cut)",
    "Eggs (×12)",
    "Butter",
    "Pork belly slab (lechon kawali)",
    "Bay leaves",
    "Beef shank with bone (bulalo)",
    "Pork shoulder or belly (BBQ)",
    "Chicken thighs or leg quarters",
    "Annatto powder (atsuete)",
    "Chicken liver",
    "Bacon strips",
    "Garlic powder",
    "Black pepper",
    "Calamansi"
  ],
  "Clean Eating": [
    "Chicken breast",
    "Brown rice",
    "Kangkong or pechay",
    "Garlic",
    "Onion",
    "Lean pork (small amount)",
    "Kalabasa (squash)",
    "Eggplant (talong)",
    "Ampalaya (bitter melon)",
    "Okra",
    "Sitaw",
    "Bagoong (small jar)",
    "Red lentils",
    "Sinigang mix",
    "Tilapia (whole or fillet)",
    "Ginger",
    "Mung beans (mongo)",
    "Malunggay leaves",
    "Rolled oats",
    "Ripe mango",
    "Carabao milk or low-fat milk",
    "Chia seeds",
    "Honey",
    "Fish sauce"
  ],
  "Pescatarian": [
    "Salmon belly or fillet",
    "Sinigang mix",
    "Kangkong",
    "Sitaw",
    "Radish (labanos)",
    "Tilapia or bangus fillet",
    "Banana leaf or foil",
    "Taro leaves (gabi)",
    "Shrimp (peeled)",
    "Oyster sauce",
    "Sesame oil",
    "Bangus belly cuts",
    "Tomato",
    "Red onion",
    "Cane vinegar",
    "Firm tofu",
    "Eggplant",
    "Natural peanut butter",
    "Annatto powder",
    "Bagoong alamang",
    "Canned tuna in oil (×2)",
    "Mayonnaise",
    "Green chili",
    "Calamansi (×10)",
    "Garlic",
    "Onion",
    "Fish sauce",
    "Soy sauce",
    "Cooking oil"
  ],
  "Diabetic-Friendly": [
    "Chicken breast",
    "Brown rice",
    "Ginger",
    "Garlic",
    "Onion",
    "Fish sauce",
    "Calamansi",
    "Tilapia fillet",
    "Ampalaya (bitter melon)",
    "Eggs",
    "Sinigang mix (low sodium)",
    "Kangkong",
    "Sitaw",
    "Radish",
    "Mung beans (mongo)",
    "Malunggay leaves",
    "Tomato",
    "Broccoli",
    "Sayote (chayote)",
    "Zucchini",
    "Carrots",
    "Olive oil",
    "Paprika",
    "Dried oregano",
    "Pechay (bok choy)",
    "Spring onion",
    "Low-sodium chicken broth"
  ],
  "Low Sodium": [
    "Bangus fillet",
    "Ginger",
    "Garlic",
    "Calamansi (×10)",
    "Sesame oil",
    "Spring onion",
    "Chicken thighs (bone-in)",
    "Sayote",
    "Malunggay leaves",
    "Unsalted chicken broth",
    "Chicken breast",
    "Dried oregano",
    "Garlic powder",
    "Paprika",
    "Olive oil",
    "Mung beans (mongo)",
    "Kalabasa (squash)",
    "Spinach or malunggay",
    "Egg whites",
    "Eggs",
    "Tomato",
    "Olive oil",
    "Black pepper",
    "Camote (sweet potato)",
    "Canned tuna in water (no salt added)",
    "Dried rosemary"
  ],
  "TTC": [
    "Spinach",
    "Malunggay/Moringa leaves",
    "Broccoli",
    "Edamame frozen",
    "Cherry tomatoes",
    "Avocado",
    "Banana",
    "Mixed berries frozen",
    "Salmon fillet",
    "Bangus fillet",
    "Lean beef strips",
    "Eggs",
    "Oat milk",
    "Red lentils",
    "Quinoa",
    "Brown rice",
    "Rolled oats",
    "Pumpkin seeds",
    "Chia seeds",
    "Sesame seeds",
    "Olive oil",
    "Calamansi",
    "Garlic",
    "Ginger",
    "Turmeric",
    "Low-sodium soy sauce",
    "Low-sodium broth",
    "Oyster sauce",
    "Honey",
    "Folic acid supplement"
  ],
  "Calorie Deficit": [
    "Chicken breast",
    "Day-old rice",
    "Eggs",
    "Garlic",
    "Soy sauce",
    "Sesame oil",
    "Spring onion",
    "Bangus fillet",
    "Sinigang mix",
    "Kangkong",
    "Sitaw",
    "Egg whites",
    "Pechay (bok choy)",
    "Tomato",
    "Onion",
    "Sayote",
    "Malunggay leaves",
    "Low-sodium chicken broth",
    "Canned tuna in water",
    "Cabbage",
    "Cucumber",
    "Calamansi",
    "Camote (sweet potato)",
    "Carrots",
    "Fish sauce (minimal use)"
  ]
}
